server.port=${PORT:8080}
google.ai.api.key=${GEMINI_API_KEY}
gemini.api.model=${GEMINI_API_MODEL:gemini-2.5-flash}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:seedbankdb}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
